version: '3.8'
services:
  api:
    build: ./back
    ports:
      - "3000:3000"
    working_dir: /app
    restart: unless-stopped
  front:
    build: ./front
    ports:
      - "8080:80"
    restart: unless-stopped 