version: '3.8'
services:
  api:
    image: rg.fr-par.scw.cloud/namespace-reungoat-nathan/my-api:latest
    ports:
      - "3000:3000"
    working_dir: /app
    restart: unless-stopped
  front:
    image: rg.fr-par.scw.cloud/namespace-reungoat-nathan/my-front:latest
    ports:
      - "8080:80"
    restart: unless-stopped 