name: Deploy to Scaleway

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      SCW_REGISTRY: ${{ secrets.SCW_REGISTRY }}
      SCW_ORGANIZATION_ID: ${{ secrets.SCW_ORGANIZATION_ID }}
      SCW_PROJECT_ID: ${{ secrets.SCW_PROJECT_ID }}
      SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
      SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
      BACK_IMAGE: ${{ secrets.SCW_REGISTRY }}/back:latest
      FRONT_IMAGE: ${{ secrets.SCW_REGISTRY }}/front:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Déploiement sur Scaleway Serverless Containers (exemple CLI)
      - name: Set up Scaleway CLI
        uses: scaleway/action-scw@v0
        with:
          access-key: ${{ secrets.SCW_ACCESS_KEY }}
          secret-key: ${{ secrets.SCW_SECRET_KEY }}
          default-project-id: ${{ secrets.SCALEWAY_PROJECT_ID }}
          default-organization-id: ${{ secrets.SCALEWAY_ORG_ID }}
          save-config: true
          export-config: true

      - name: Update backend container image
        run: |
          scw config init with-key $SCW_ACCESS_KEY $SCW_SECRET_KEY $SCW_PROJECT_ID $SCW_ORGANIZATION_ID
          scw container container update ${{ secrets.BACK_CONTAINER_ID }} image=$BACK_IMAGE

      - name: Update frontend container image
        run: |
          scw container container update  ${{ secrets.FRONT_CONTAINER_ID }} image=$FRONT_IMAGE

# Remplace <BACK_CONTAINER_ID> et <FRONT_CONTAINER_ID> par les IDs de tes containers Scaleway.
# Ajoute les secrets nécessaires dans les paramètres GitHub (voir README pour la liste complète).
