name: Build, Push & Deploy to Scaleway

on:
  push:
    branches: [main]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest
    env:
      BACK_IMAGE: rg.fr-par.scw.cloud/namespace-reungoat-nathan/my-api:latest
      FRONT_IMAGE: rg.fr-par.scw.cloud/namespace-reungoat-nathan/my-front:latest
      # ... autres variables

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Scaleway Container Registry
        uses: docker/login-action@v3
        with:
          registry: rg.fr-par.scw.cloud
          username: ${{ secrets.SCW_REGISTRY_USER }}
          password: ${{ secrets.SCW_REGISTRY_PASSWORD }}

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: ./back
          file: ./back/Dockerfile
          push: true
          tags: ${{ env.BACK_IMAGE }}

      - name: Build and push Front image
        uses: docker/build-push-action@v5
        with:
          context: ./front
          file: ./front/Dockerfile
          push: true
          tags: ${{ env.FRONT_IMAGE }}

      - name: Set up Scaleway CLI
        uses: scaleway/action-scw@v0
        with:
          access-key: ${{ secrets.SCW_ACCESS_KEY }}
          secret-key: ${{ secrets.SCW_SECRET_KEY }}
          default-project-id: ${{ secrets.SCW_PROJECT_ID }}
          default-organization-id: ${{ secrets.SCW_ORGANIZATION_ID }}
          save-config: true
          export-config: true

      - name: Update backend container image
        run: |
          scw container container update ${{ secrets.BACK_CONTAINER_ID }} registry-image=$BACK_IMAGE

      - name: Update frontend container image
        run: |
          scw container container update ${{ secrets.FRONT_CONTAINER_ID }} registry-image=$FRONT_IMAGE
