name: Build, Push & Deploy to Scaleway

on:
  push:
    branches: [main]

jobs:

  build-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Scaleway Container Registry
        uses: docker/login-action@v3
        with:
          registry: rg.fr-par.scw.cloud
          username: ${{ secrets.SCW_REGISTRY_USER }}
          password: ${{ secrets.SCW_REGISTRY_PASSWORD }}

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: ./back
          file: ./back/Dockerfile
          push: true
          tags: ${{ secrets.SCW_REGISTRY }}

  deploy-api:
    needs: build-api
    outputs:
      BACKEND_URL: ${{ steps.backend-url.outputs.BACKEND_URL }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set output BACKEND_URL
        run: echo "BACKEND_URL=$BACKEND_URL" >> $GITHUB_ENV


      - name: Set up Scaleway CLI
        uses: scaleway/action-scw@v0
        with:
          access-key: ${{ secrets.SCW_ACCESS_KEY }}
          secret-key: ${{ secrets.SCW_SECRET_KEY }}
          default-project-id: ${{ secrets.SCW_PROJECT_ID }}
          default-organization-id: ${{ secrets.SCW_ORGANIZATION_ID }}
          save-config: true
          export-config: true

      - name: Update backend container & get backend URL
        id: backend-url
        run: |
          CONTAINER_ID="${{ secrets.BACK_CONTAINER_ID }}"

          UPDATE_RESULT=$(scw container container update "$CONTAINER_ID" registry-image=${{ secrets.SCW_REGISTRY }} --output json)
          DOMAIN=$(echo "$UPDATE_RESULT" | jq -r '.domain_name')
          BACKEND_URL="https://$DOMAIN"
          echo "BACKEND_URL=$BACKEND_URL" >> $GITHUB_OUTPUT

  build-front:
    needs: deploy-api
    env:
      FRONT_IMAGE: rg.fr-par.scw.cloud/namespace-reungoat-nathan/my-front:latest
      BACKEND_URL: ${{ needs.deploy-api.outputs.BACKEND_URL }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Inject VITE_API_URL
        run: echo "VITE_API_URL=${BACKEND_URL}" > front/.env.production

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Scaleway Container Registry
        uses: docker/login-action@v3
        with:
          registry: rg.fr-par.scw.cloud
          username: ${{ secrets.SCW_REGISTRY_USER }}
          password: ${{ secrets.SCW_REGISTRY_PASSWORD }}

      - name: Build and push Front image
        uses: docker/build-push-action@v5
        with:
          context: ./front
          file: ./front/Dockerfile
          push: true
          tags: ${{ env.FRONT_IMAGE }}

  deploy-front:
    needs: [build-front, deploy-api]
    runs-on: ubuntu-latest
    env:
      FRONT_IMAGE: rg.fr-par.scw.cloud/namespace-reungoat-nathan/my-front:latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Scaleway CLI
        uses: scaleway/action-scw@v0
        with:
          access-key: ${{ secrets.SCW_ACCESS_KEY }}
          secret-key: ${{ secrets.SCW_SECRET_KEY }}
          default-project-id: ${{ secrets.SCW_PROJECT_ID }}
          default-organization-id: ${{ secrets.SCW_ORGANIZATION_ID }}
          save-config: true
          export-config: true

      - name: Update frontend container image
        run: |
          scw container container update ${{ secrets.FRONT_CONTAINER_ID }} registry-image=${{ env.FRONT_IMAGE }}
