name: Docker Build & Push to Scaleway

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Scaleway Container Registry
        uses: docker/login-action@v3
        with:
          registry: rg.fr-par.scw.cloud
          username: ${{ secrets.SCW_REGISTRY_USER }}
          password: ${{ secrets.SCW_REGISTRY_PASSWORD }}

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: ./back
          file: ./back/Dockerfile
          push: true
          tags: rg.fr-par.scw.cloud/namespace-reungoat-nathan/my-api:latest

      - name: Build and push Front image
        uses: docker/build-push-action@v5
        with:
          context: ./front
          file: ./front/Dockerfile
          push: true
          tags: rg.fr-par.scw.cloud/namespace-reungoat-nathan/my-front:latest
          build-args: |
            VITE_API_URL=rg.fr-par.scw.cloud/namespace-reungoat-nathan/my-api:latest
