name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  back:
    name: Build & Test API (Node.js)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: devops-dev/back
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install
      - run: npx prisma generate
      - run: npm test

  front:
    name: Build Front (Node.js)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: devops-dev/front
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm install
      - run: npm run build
